package com.badrani.keygrain.data

import org.junit.Assert.assertEquals
import org.junit.Test

class KeygrainTest {

    // Test vectors from vectors.json (generated by Python reference implementation)
    data class Vector(
        val secretUtf8: String,
        val email: String,
        val length: Int,
        val symbols: String,
        val salt: String,
        val expected: String
    )

    private val vectors = listOf(
        Vector("my-master-secret", "test@gmail.com", 20, "!@#\$%&*-_=+?", "", "jU8D8b@epA_=X\$4CN7&4"),
        Vector("my-master-secret", "test@outlook.com", 20, "!@#\$%&*-_=+?", "", "FQ9a3aV2bY2Wdf75\$Y4X"),
        Vector("my-master-secret", "TEST@Gmail.com", 20, "!@#\$%&*-_=+?", "", "jU8D8b@epA_=X\$4CN7&4"),
        Vector("my-master-secret", "user@custom.org", 16, "!@#\$%&*-_=+?", "", "uktU-g7kXY&zPQ7k"),
        Vector("my-master-secret", "test@gmail.com", 20, "!@#\$%&*-_", "", "rX8K@m%esG_AX*4FR*&4"),
        Vector("my-master-secret", "test@gmail.com", 20, "!@#\$%&*-_=+?", "2024", "NUWrnAkPf8Xb@R7WV66\$"),
        Vector("different-secret", "test@gmail.com", 20, "!@#\$%&*-_=+?", "", "c\$RV9KGJppwJeUp_c3Y8"),
        Vector("my-master-secret", "test@gmail.com", 32, "!@#\$%&*-_=+?", "", "kPYHb2dYUk\$qP6bjbzLAV5A%p3j6T5U_"),
    )

    @Test
    fun testAllVectors() {
        for (v in vectors) {
            val result = Keygrain.derivePassword(
                secret = v.secretUtf8.toByteArray(),
                email = v.email,
                length = v.length,
                symbols = v.symbols,
                salt = v.salt
            )
            assertEquals(
                "Failed for ${v.email} (len=${v.length}, salt='${v.salt}')",
                v.expected,
                result
            )
        }
    }

    @Test
    fun testDeterministic() {
        val a = Keygrain.derivePassword("secret".toByteArray(), "x@y.com")
        val b = Keygrain.derivePassword("secret".toByteArray(), "x@y.com")
        assertEquals(a, b)
    }

    @Test
    fun testCaseInsensitiveEmail() {
        val a = Keygrain.derivePassword("secret".toByteArray(), "User@Example.COM")
        val b = Keygrain.derivePassword("secret".toByteArray(), "user@example.com")
        assertEquals(a, b)
    }

    @Test(expected = IllegalArgumentException::class)
    fun testMinLengthRejected() {
        Keygrain.derivePassword("secret".toByteArray(), "a@b.com", length = 7)
    }

    @Test(expected = IllegalArgumentException::class)
    fun testEmptySymbolsRejected() {
        Keygrain.derivePassword("secret".toByteArray(), "a@b.com", symbols = "")
    }
}
