"""Cross-platform end-to-end verification (U3).

The fixture ``sync-vectors.json`` (repo root, alongside vectors.json — a SHARED
cross-platform vector also consumed by the JS and Kotlin suites) is generated by
``ci/gen-sync-vectors.mjs`` using the ACTUAL extension JavaScript (extension/shared/{keygrain,sync,totp,
ssh}.js) as an INDEPENDENT oracle. This test:

1. Pins the Python-computed lookup_id / auth_password / encryption_key against
   the JS-generated fixture BIT-FOR-BIT (the cross-platform sync-crypto contract,
   incl. the reviewers' "pin an auth_password vector" item).
2. Feeds the fixture's server blob + metadata to a MOCKED server GET and runs the
   REAL sync -> cache -> get path (download decrypts the JS-produced blob with the
   Python-computed key -> proves key agreement through an actual decrypt).
3. Asserts each `get` (password / totp / ssh) equals the extension-generated
   reference value.

If any of these drift, Python and the extension have diverged on the sync path.
"""

import io
import json
import pathlib
import time

import pytest

from keygrain import cli, cache as cache_mod, sync_client as sc
from keygrain.totp import derive_totp_seed, generate_totp

FIXTURE_PATH = pathlib.Path(__file__).resolve().parents[2] / "sync-vectors.json"
FIXTURE = json.loads(FIXTURE_PATH.read_text())

SECRET = FIXTURE["secret"]
EMAIL = FIXTURE["email"]


class _FakeResponse(io.BytesIO):
    def __init__(self, body):
        super().__init__(body)
        import email.message
        self.headers = email.message.Message()

    def __enter__(self):
        return self

    def __exit__(self, *a):
        self.close()
        return False


@pytest.fixture
def home(tmp_path, monkeypatch):
    h = str(tmp_path / "kg")
    monkeypatch.setattr(cache_mod, "keygrain_home", lambda: h)
    monkeypatch.setenv("KG_SECRET", SECRET)
    return h


def run(monkeypatch, capsys, argv):
    monkeypatch.setattr("sys.argv", ["keygrain"] + argv)
    code = 0
    try:
        cli.main()
    except SystemExit as e:
        code = e.code or 0
    cap = capsys.readouterr()
    return code, cap.out, cap.err


# --- 1. Bit-for-bit derivation agreement (cross-platform contract) -----------

def test_lookup_id_matches_extension():
    assert sc.derive_lookup_id(SECRET.encode(), EMAIL) == FIXTURE["lookup_id"]


def test_auth_password_matches_extension():
    # The reviewers' "pin an auth_password vector" item, sourced from the JS oracle.
    assert sc.derive_auth_password(SECRET.encode(), EMAIL) == FIXTURE["auth_password"]


def test_encryption_key_matches_extension():
    assert sc.derive_encryption_key(SECRET.encode(), EMAIL).hex() == FIXTURE["encryption_key_hex"]


def test_totp_seed_matches_extension():
    # Time-independent cross-platform check of the derived TOTP seed.
    totp_svc = next(s for s in FIXTURE["services"] if "totp_seed_hex" in s["expected"])
    seed = derive_totp_seed(SECRET.encode(), EMAIL, totp_svc["site"])
    assert seed.hex() == totp_svc["expected"]["totp_seed_hex"]


# --- 2 + 3. Real sync -> cache -> get against the JS-produced blob ------------

def _do_sync(monkeypatch, capsys):
    body = json.dumps(FIXTURE["server_response"]).encode()
    monkeypatch.setattr(sc, "_urlopen", lambda req, timeout=None: _FakeResponse(body))
    return run(monkeypatch, capsys, ["sync", "--email", EMAIL, "--secret-env", "KG_SECRET"])


def test_sync_decrypts_js_blob_and_caches_all_services(home, monkeypatch, capsys):
    code, out, err = _do_sync(monkeypatch, capsys)
    assert code == 0, err
    assert f"Synced {len(FIXTURE['services'])} service(s)" in err
    # Decrypted services match the fixture (site/email/params survive the round-trip).
    data = cache_mod.read_cache(SECRET.encode(), EMAIL)
    cached = {(s.get("site"), s.get("email")): s for s in data["services"]}
    for fsvc in FIXTURE["services"]:
        key = (fsvc["site"], fsvc["email"])
        assert key in cached, key
        assert cached[key]["id"] == fsvc["id"]  # real UUIDs survive sanitization
        assert cached[key]["updated_at"] == fsvc["updated_at"]


def test_get_password_matches_extension(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    # github.com — unambiguous single site.
    code, out, err = run(monkeypatch, capsys,
                         ["get", "--site", "github.com", "--secret-env", "KG_SECRET"])
    assert code == 0, err
    gh = next(s for s in FIXTURE["services"] if s["site"] == "github.com")
    assert out.strip() == gh["expected"]["password"]


def test_get_shared_site_disambiguated_by_service_email(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    shared = [s for s in FIXTURE["services"] if s["site"] == "shared.example"]
    assert len(shared) == 2  # sanity: the fixture exercises --service-email
    for svc in shared:
        code, out, err = run(monkeypatch, capsys, [
            "get", "--site", "shared.example",
            "--service-email", svc["email"], "--secret-env", "KG_SECRET",
        ])
        assert code == 0, err
        assert out.strip() == svc["expected"]["password"]


def test_get_shared_site_ambiguous_without_email(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    code, out, err = run(monkeypatch, capsys,
                         ["get", "--site", "shared.example", "--secret-env", "KG_SECRET"])
    assert code != 0
    assert "alice@keygrain.example" in err and "bob@keygrain.example" in err


def test_get_totp_uses_cross_platform_seed(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    totp_svc = next(s for s in FIXTURE["services"] if "totp_seed_hex" in s["expected"])
    code, out, err = run(monkeypatch, capsys, [
        "get", "--site", totp_svc["site"], "--totp", "--secret-env", "KG_SECRET",
    ])
    assert code == 0, err
    seed = bytes.fromhex(totp_svc["expected"]["totp_seed_hex"])
    assert out.strip() == generate_totp(seed, int(time.time()))


def test_get_ssh_matches_extension(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    ssh_svc = next(s for s in FIXTURE["services"] if "ssh_authorized_keys" in s["expected"])
    code, out, err = run(monkeypatch, capsys, [
        "get", "--site", ssh_svc["site"], "--ssh", "--secret-env", "KG_SECRET",
    ])
    assert code == 0, err
    assert out.strip() == ssh_svc["expected"]["ssh_authorized_keys"]


def test_get_by_id_matches(home, monkeypatch, capsys):
    _do_sync(monkeypatch, capsys)
    gh = next(s for s in FIXTURE["services"] if s["site"] == "github.com")
    code, out, err = run(monkeypatch, capsys,
                         ["get", "--id", gh["id"], "--secret-env", "KG_SECRET"])
    assert code == 0, err
    assert out.strip() == gh["expected"]["password"]
